### ISSUE TITLE
Separate Components

### ISSUE THREAD

**Issue by heshanlk** [kalinchernev/drupal_block_reactive#2]
Is it possible to separate the CommentBox and Comment components to two separate files and import using require or similar method?

**Comment by kalinchernev** [comment]
Yes, sure. Feel free to fork, clone and experiment! :)
I'm closing this one as it's not really an issue.

**Comment by heshanlk** [comment]
I assume we need to include the Webpack in tot he package.json right? if we separate components in the separate files. That's what I learned from couple of tutorials.

**Comment by kalinchernev** [comment]
My saying was actually that you do NOT need webpack to develop react.
There are many resources on the web for any tool you want to learn more, but you'll surely have to have an idea what is babel, node.js, bower, gulp/grunt, etc. And try to experiment with small apps built with these, but keep your end goal in mind, that's more or less the high-level approach.
When I was playing with react and got frustrated with the whole toolchain i had to learn over a weekend, for example, I read few articles from [this blog](https://daveceddia.com/). Pretty down to earth I'd say.

**Comment by heshanlk** [comment]
Thanks, appreciate that. I'll take look :).

**Comment by heshanlk** [comment]
I think I figured this out, checkout the fork when you get a chance, it is more cleaner that way I guess. Your code really helped to understand the whole concept so thank you 👍 .

**Comment by kalinchernev** [comment]
@heshanlk well done, you're definitely in the good way! :)
